Feature/redesign next upgrade
helium/helium-vote pull request #126
Opened 2024-03-08 18:28 UTC by bryzettler

2024-03-11 20:57 UTC, ChewingGlass requested changes

2024-03-11 20:57 UTC, ChewingGlass commented on src/components/Positions.tsx
> +export const Positions: FC<{ className?: string }> = ({ className = "" }) => {
className not used

2024-03-11 20:57 UTC, ChewingGlass commented on src/app/[network]/positions/page.tsx
> +  searchParams,
params aren't used

2024-03-11 20:57 UTC, ChewingGlass commented on src/app/[network]/positions/page.tsx
> +      <Header hideHero={true} route="/$network/positions" />
Does this work without doing explicit substitution of current network?

2024-03-11 20:57 UTC, ChewingGlass commented on src/lib/utils.ts
> +          console.log(tx.signatures);
still need this?

2024-03-11 20:57 UTC, ChewingGlass commented on src/app/[network]/proposals/[proposalKey]/page.tsx
> +  const { name } = await getProposalContent(pKey);
This will be a pretty hefty call. Is this cached at all? If not, how do we enable caching? Would be nice if we only did this 1/day or something

2024-03-11 20:57 UTC, ChewingGlass commented on src/components/VoteOptions.tsx
> +    error: relErr,
Neither this error nor voteErr used anywhere. Should probably toast or something?

2024-03-11 20:57 UTC, ChewingGlass commented on src/components/CreatePositionModal.tsx
> +  const { error: createPositionError, createPosition } = useCreatePosition();
error isn't used

2024-03-11 22:07 UTC, bryzettler commented on src/components/Proposals.tsx
> +            {network === "hnt" && children}
Legacy proposals are fetched via the server  and render as server components. This Proposals.tsx is a client component. Ill move this logic to the route and just pass children

2024-03-11 22:11 UTC, bryzettler commented on src/lib/utils.ts
> +          console.log(tx.signatures);
nope

2024-03-11 22:19 UTC, bryzettler commented on src/app/[network]/proposals/[proposalKey]/page.tsx
> +  const { name } = await getProposalContent(pKey);
yup, any fetch on server side components is cached. Ill up the revalidation 
https://github.com/helium/helium-vote/blob/feature/redesign-next-upgrade/src/lib/utils.ts#L342

2024-03-11 23:10 UTC, bryzettler commented on src/components/VoteOptions.tsx
> +    error: relErr,
added try catch around the logic

2024-03-12 19:52 UTC, ChewingGlass submitted a review, later dismissed

2024-03-12 19:52 UTC, ChewingGlass commented on src/components/LockTokensForm.tsx
> +                tokens to be available for reclaiming. We are using 2 years as
```suggestion
                tokens to be available for reclaiming. 2 years is used as
```

2024-03-12 19:52 UTC, ChewingGlass commented on src/components/NetworkBanner.tsx
> +              tokens depending on the network you&apos;re on
```suggestion
              tokens depending on the subnetwork
```

2024-03-18 21:24 UTC, ChewingGlass approved these changes

2024-03-28 21:50 UTC, ChewingGlass submitted a review, later dismissed

2024-04-03 20:18 UTC, abhay approved these changes
Let's land it!

2024-04-03 20:47 UTC, merged