Add MOBILE proposals
helium/helium-vote pull request #92
Opened 2023-12-04 23:03 UTC by ChewingGlass

2023-12-04 23:28 UTC, abhay commented on mobile-proposals.json
> +    "uri": "https://github.com/KeithRettig/HIP/blob/2023Q4_ModularVoting/2023Q4_ModularVoting__Summary",
ideally this is moved into this repo instead.

2023-12-05 03:08 UTC, abhay requested changes
Added changes from candidates and vote text.

2023-12-05 03:08 UTC, abhay commented on mobile-proposals.json
> +    "uri": "https://github.com/KeithRettig/HIP/blob/2023Q4_ModularVoting/2023Q4_ModularVoting__Summary",
```suggestion
    "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__00__Summary.md",
```

2023-12-05 03:08 UTC, abhay commented on mobile-proposals.json
> +      { "uri": null, "name": "greenz" }
```suggestion
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_heatedlime.md", "name": "Heated Lime" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_keithrettig.md", "name": "Keith Rettig" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_Capc0m.md", "name": "Max Gold" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_kennyy6399.md", "name": "Kennyy" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_cheflifeworld.md", "name": "cheflifeworld" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_Erfanjhan.md", "name": "Erfanjhan" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_Unikt39.md", "name": "Unikt39" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_Brainstormer.md", "name": "Brainstormer" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_kevin314.md", "name": "KΞ7IN" },
      { "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__CandidateMessage_greenzdewi.md", "name": "greenz" }
```

2023-12-05 03:20 UTC, ChewingGlass commented on mobile-proposals.json
> +      { "uri": null, "name": "greenz" }
URIs don't do anything yet. Not sure if they will be markdown when they do, so not accepting this change.

2023-12-05 04:49 UTC, abhay commented on mobile-proposals.json
> +    "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/ebbe80bc2d992e5d9c64530391523683c67c8c0e/2023Q4__MOBILE__00__Summary.md",
```suggestion
    "uri": "https://gist.githubusercontent.com/hiptron/036867431eb2153a52babe30fb5dbdf3/raw/50f037e807ad844e87e0ff335ffe605bedb48d57/2023Q4__MOBILE__00__Summary.md",
```

2023-12-05 15:51 UTC, abhay approved these changes

2023-12-05 15:54 UTC, merged